@startuml
actor :Librarian: as lib
actor :User:
left to right direction

rectangle "System" {
    (Enter User ID) as enterID
    (Get ID of Borrowed Book) as borrow
    (Validate IDs) as validate
    (Assign Book ID to User) as assign
    (Set Due Date) as setDue
    (Click Confirm) as confirm
    (Send Confirmation Message) as confirmMsg
}

lib -> enterID

enterID ..> validate : includes

lib --> borrow

borrow ..> validate : includes


lib --> assign
lib --> setDue
lib --> confirm
confirm ..> confirmMsg :includes
User <-- confirmMsg : notifies
@enduml