@startuml

' Define conceptual classes
object Library {
  Name
  Location
}

object Book {
  Details
  ISBN
}

object Stock {
  Quantity
}

object User {
  ID
}

object Librarian {
  ID
}

object Borrow {
  Issue Date
  Due Date
}

object Fine {
  Amount
  Status
}

' Define associations
Library "1" --> "*" Book : Holds
Library "1" --> "*" User : Has
Library "1" --> "*" Librarian : Employs
Book "1" --> "1" Stock : Has
User "1" --> "*" Borrow : Borrows
Borrow "1" --> "1" Book : For
Borrow "0..1" --> "1" Fine : Related to
Librarian "1" --> "*" Borrow : Processes

@enduml
