@startuml
left to right direction
actor Librarian as lib

rectangle "System" {
    (Add Book) as Add
    (Edit Book Info) as Edit
    (Remove Book) as Remove
    (Add Book Info to DB) as DBadd
    (Edit Book Info in DB) as DBedit
    (Remove Book from DB) as DBremove
    (Find the Book to Edit) as edit2
    (Run SQL Add Statement) as SqlAdd
    (Run SQL Edit Statement) as SqlEdit
    (Run SQL Remove Statement) as SqlRemove
    (Confirmation or Error Message) as Confirm
    (Return Correct book) as foundBook
}


lib -down-> Add : Enter required info
lib -down-> Edit : Enter Book ID to Edit
lib -down-> Remove : Enter Book ID to Remove

Add .down.> DBadd : includes
DBadd .down.> SqlAdd : Process Add Request
SqlAdd .down.> Confirm : Execute Add in Database
Confirm -up-> lib : Notify

Edit .down.> edit2 : includes
edit2 .down.> foundBook : Fetch Book Info
foundBook ..> DBedit : Found Book to Edit
DBedit -down.> Confirm : Run SQL Edit Statement
Confirm -up-> lib : Notify

Remove -down.> DBremove : includes
DBremove -down.> SqlRemove : Process Remove Request
SqlRemove -down.> Confirm : Execute Remove in Database
Confirm -up-> lib : Notify

@enduml