@startuml
left to right direction
actor :User:

rectangle "System" {
    (Enter Search Query) as search
    (Select Book) as sb
    (Click Reserve Button) as reserve
    (Borrow Book) as borrow
    (Book is Reserved) as reserved
    (Process Query) as pq
    (Check Availability) as ca
}

User --> search
search ..> pq: <<includes>>

User --> sb
sb --> reserve : <<out of stock>>
sb --> borrow : <<in stock>>
sb ..> ca : <<includes>>

reserve --> reserved
borrow --> reserved
@enduml
