@startuml
'https://plantuml.com/state-diagram
!pragma layout smetana
[*] --> LoginScreen

LoginScreen --> HomePage : "Login successfully"
LoginScreen --> SignUpPage : "Create new account"
LoginScreen --> LoginScreen : "Login fails"
SignUpPage -->HomePage : "Account is created"
HomePage --> SettingsPage : "User clicks Settings Icon"
SettingsPage --> HomePage : "User clicks Back/ log out"

HomePage --> SearchPage : "User clicks Search Icon"
HomePage --> NotificationsPage : "User clicks Notification Icon"
HomePage --> BookDetailsPage : "User clicks on specific Book"
HomePage --> AboutPage : "User clicks About Icon"

@enduml